version: '4.9'

services:
  db:
    image: postgres:15-alpine
    container_name: laundry_db
    restart: always
    environment:
      POSTGRES_USER: laundry_user
      POSTGRES_PASSWORD: laundry_password
      POSTGRES_DB: laundry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: